### ISSUE TITLE
Does the author still maintain this project, 2020, cannot download

### ISSUE THREAD

**Issue by kexuebin** [cannium/FamilySearchDownloader#1]
Does the author still maintain this project, 2020, cannot download

**Comment by cannium** [comment]
No, not any more. 
I take a look at familysearch.org, it requires authentication now. And a little curious, what's your purpose of downloading those contents?

**Comment by kexuebin** [comment]
The website is slow in network speed and difficult to load, which is very inconvenient for searching



---Original---
